# Specify dist until Travis CI default Runner OS updates to one
# with glibc version required by newer Node versions
# See: https://github.com/nodejs/node/issues/42351#issuecomment-1068424442
dist: jammy
language: node_js
sudo: false
node_js:
  - lts/*
addons:
  chrome: stable
before_install:
  # Install Bun
  - curl -fsSL https://bun.sh/install | bash
  - export PATH="$HOME/.bun/bin:$PATH"
  - bun --version
install:
  # Install dependencies with Bun
  - bun install
  # Install Chrome for Puppeteer
  - npx puppeteer browsers install chrome
script:
  # Run linting
  - bun run lint
  # Run build
  - bun run build
  # Run tests
  - bun run test:auto
