name: 'Pull Request Checks'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'images/**'
      - '.github/workflows/prs.yml'
      - '*.json'
      - '*.js'
      - '*.css'
      - '!test/demo/**'

jobs:
  run_checks:
    name: Run test tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package.json
          node-version: lts/*

      - name: Setup environment and install dependencies
        run: |
          npm install -g grunt-cli
          npm ci

      - name: Install Chrome for Puppeteer
        run: |
          rm -rf "$HOME/.cache/puppeteer/chrome"
          INSTALL_OUTPUT=$(npx @puppeteer/browsers install chrome@127.0.6533.88 --path "$HOME/.cache/puppeteer")
          echo "$INSTALL_OUTPUT"
          CHROME_PATH=$(echo "$INSTALL_OUTPUT" | tail -n 1 | awk '{print $2}')
          echo "PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH" >> "$GITHUB_ENV"

      - name: Run tests
        run: |
          npm run test
