name: 'Pull Request Checks'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'images/**'
      - '.github/workflows/prs.yml'
      - '*.json'
      - '*.js'
      - '*.css'
      - '!test/demo/**'

jobs:
  run_checks:
    name: Run test tasks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Run tests
        run: bun run test:auto

